export default [
  {
    id: "1",
    product_id: "p1",
    name: "T-shirt",
    description: "Cotton t-shirt",
    price: "19.99",
    rating: "4.5",
    type: "clothes",
  },
  {
    id: "2",
    product_id: "p2",
    name: "Jeans",
    description: "Slim fit jeans",
    price: "49.99",
    rating: "4.2",
    type: "clothes",
  },
  {
    id: "3",
    product_id: "p3",
    name: "Sneakers",
    description: "Running shoes",
    price: "79.99",
    rating: "4.7",
    type: "clothes",
  },
  {
    id: "4",
    product_id: "p4",
    name: "TV",
    description: "55-inch 4K Smart TV",
    price: "599.99",
    rating: "4.8",
    type: "electronics",
  },
  {
    id: "5",
    product_id: "p5",
    name: "Laptop",
    description: "13-inch MacBook Pro",
    price: "1299.99",
    rating: "4.9",
    type: "electronics",
  },
  {
    id: "6",
    product_id: "p6",
    name: "Headphones",
    description: "Wireless over-ear headphones",
    price: "149.99",
    rating: "4.6",
    type: "electronics",
  },
  {
    id: "7",
    product_id: "p7",
    name: "Banana",
    description: "Fresh banana",
    price: "0.29",
    rating: "4.3",
    type: "food",
  },
  {
    id: "8",
    product_id: "p8",
    name: "Milk",
    description: "Whole milk",
    price: "2.99",
    rating: "4.1",
    type: "food",
  },
  {
    id: "9",
    product_id: "p9",
    name: "Bread",
    description: "Whole wheat bread",
    price: "1.99",
    rating: "4.4",
    type: "food",
  },
  {
    id: "10",
    product_id: "p10",
    name: "Dress",
    description: "Floral print dress",
    price: "39.99",
    rating: "4.7",
    type: "clothes",
  },
  {
    id: "11",
    product_id: "p11",
    name: "Shirt",
    description: "Button-down shirt",
    price: "29.99",
    rating: "4.3",
    type: "clothes",
  },
  {
    id: "12",
    product_id: "p12",
    name: "Sweater",
    description: "Crew neck sweater",
    price: "59.99",
    rating: "4.6",
    type: "clothes",
  },
  {
    id: "13",
    product_id: "p13",
    name: "Phone",
    description: "iPhone 12",
    price: "999.99",
    rating: "4.9",
    type: "electronics",
  },
  {
    id: "14",
    product_id: "p14",
    name: "Tablet",
    description: "10-inch Android tablet",
    price: "199.99",
    rating: "4.4",
    type: "electronics",
  },
  {
    id: "15",
    product_id: "p15",
    name: "Smartwatch",
    description: "Fitness tracker smartwatch",
    price: "129.99",
    rating: "4.7",
    type: "electronics",
  },
  {
    id: "16",
    product_id: "p16",
    name: "Apple",
    description: "Red apple",
    price: "0.49",
    rating: "4.2",
    type: "food",
  },
  {
    id: "17",
    product_id: "p17",
    name: "Eggs",
    description: "Large eggs, 12-count",
    price: "3.99",
    rating: "4.5",
    type: "food",
  },
  {
    id: "18",
    product_id: "p18",
    name: "Cereal",
    description: "Whole grain cereal",
    price: "4.99",
    rating: "4.3",
    type: "food",
  },
  {
    id: "19",
    product_id: "p19",
    name: "Skirt",
    description: "Pleated mini skirt",
    price: "34.99",
    rating: "4.6",
    type: "clothes",
  },
  {
    id: "20",
    product_id: "p20",
    name: "Jacket",
    description: "Leather biker jacket",
    price: "89.99",
    rating: "4.8",
    type: "clothes",
  },
  {
    id: "21",
    product_id: "p21",
    name: "Coat",
    description: "Winter coat",
    price: "129.99",
    rating: "4.7",
    type: "clothes",
  },
  {
    id: "22",
    product_id: "p22",
    name: "Monitor",
    description: "27-inch 4K monitor",
    price: "399.99",
    rating: "4.6",
    type: "electronics",
  },
  {
    id: "23",
    product_id: "p23",
    name: "Keyboard",
    description: "Mechanical gaming keyboard",
    price: "79.99",
    rating: "4.4",
    type: "electronics",
  },
  {
    id: "24",
    product_id: "p24",
    name: "Mouse",
    description: "Wireless mouse",
    price: "29.99",
    rating: "4.3",
    type: "electronics",
  },
  {
    id: "25",
    product_id: "p25",
    name: "Orange",
    description: "Juicy orange",
    price: "0.39",
    rating: "4.1",
    type: "food",
  },
  {
    id: "26",
    product_id: "p26",
    name: "Yogurt",
    description: "Greek yogurt",
    price: "1.49",
    rating: "4.2",
    type: "food",
  },
  {
    id: "27",
    product_id: "p27",
    name: "Cheese",
    description: "Cheddar cheese",
    price: "3.99",
    rating: "4.5",
    type: "food",
  },
  {
    id: "28",
    product_id: "p28",
    name: "Shorts",
    description: "Denim shorts",
    price: "24.99",
    rating: "4.3",
    type: "clothes",
  },
  {
    id: "29",
    product_id: "p29",
    name: "Sweatshirt",
    description: "Hooded sweatshirt",
    price: "49.99",
    rating: "4.6",
    type: "clothes",
  },
  {
    id: "30",
    product_id: "p30",
    name: "Shoes",
    description: "Leather dress shoes",
    price: "99.99",
    rating: "4.8",
    type: "clothes",
  },
  {
    id: "31",
    product_id: "p31",
    name: "Camera",
    description: "Mirrorless camera",
    price: "799.99",
    rating: "4.9",
    type: "electronics",
  },
  {
    id: "32",
    product_id: "p32",
    name: "Printer",
    description: "Wireless all-in-one printer",
    price: "129.99",
    rating: "4.7",
    type: "electronics",
  },
  {
    id: "33",
    product_id: "p33",
    name: "Speakers",
    description: "Bluetooth speakers",
    price: "69.99",
    rating: "4.6",
    type: "electronics",
  },
  {
    id: "34",
    product_id: "p34",
    name: "Apple",
    description: "Green apple",
    price: "0.49",
    rating: "4.2",
    type: "food",
  },
  {
    id: "35",
    product_id: "p35",
    name: "Butter",
    description: "Salted butter",
    price: "2.99",
    rating: "4.1",
    type: "food",
  },
  {
    id: "36",
    product_id: "p36",
    name: "Rice",
    description: "Basmati rice",
    price: "3.99",
    rating: "4.4",
    type: "food",
  },
  {
    id: "37",
    product_id: "p37",
    name: "Dress",
    description: "Maxi dress",
    price: "59.99",
    rating: "4.7",
    type: "clothes",
  },
  {
    id: "38",
    product_id: "p38",
    name: "Blouse",
    description: "Silk blouse",
    price: "39.99",
    rating: "4.3",
    type: "clothes",
  },
  {
    id: "39",
    product_id: "p39",
    name: "Sweatpants",
    description: "Jogger sweatpants",
    price: "34.99",
    rating: "4.6",
    type: "clothes",
  },
  {
    id: "40",
    product_id: "p40",
    name: "Phone",
    description: "Samsung Galaxy S21",
    price: "1099.99",
    rating: "4.9",
    type: "electronics",
  },
  {
    id: "41",
    product_id: "p41",
    name: "Tablet",
    description: "iPad Air",
    price: "599.99",
    rating: "4.4",
    type: "electronics",
  },
  {
    id: "42",
    product_id: "p42",
    name: "Earphones",
    description: "Wireless earphones",
    price: "99.99",
    rating: "4.7",
    type: "electronics",
  },
  {
    id: "43",
    product_id: "p43",
    name: "Grapes",
    description: "Red grapes",
    price: "1.99",
    rating: "4.3",
    type: "food",
  },
  {
    id: "44",
    product_id: "p44",
    name: "Mango",
    description: "Ripe mango",
    price: "1.49",
    rating: "4.2",
    type: "food",
  },
  {
    id: "45",
    product_id: "p45",
    name: "Pizza",
    description: "Margherita pizza",
    price: "9.99",
    rating: "4.5",
    type: "food",
  },
  {
    id: "46",
    product_id: "p46",
    name: "Trousers",
    description: "Formal trousers",
    price: "49.99",
    rating: "4.3",
    type: "clothes",
  },
  {
    id: "47",
    product_id: "p47",
    name: "Blazer",
    description: "Navy blazer",
    price: "79.99",
    rating: "4.6",
    type: "clothes",
  },
  {
    id: "48",
    product_id: "p48",
    name: "Shirt",
    description: "Printed shirt",
    price: "34.99",
    rating: "4.8",
    type: "clothes",
  },
  {
    id: "49",
    product_id: "p49",
    name: "Laptop",
    description: "15-inch Windows laptop",
    price: "899.99",
    rating: "4.9",
    type: "electronics",
  },
  {
    id: "50",
    product_id: "p50",
    name: "Headset",
    description: "Gaming headset",
    price: "69.99",
    rating: "4.7",
    type: "electronics",
  },
  {
    id: "51",
    product_id: "clothes1",
    name: "T-shirt",
    description: "Cotton t-shirt",
    price: "19.99",
    rating: "4.5",
    type: "clothes",
  },
  {
    id: "52",
    product_id: "electronics1",
    name: "Smartphone",
    description: "High-end smartphone",
    price: "699.99",
    rating: "4.8",
    type: "electronics",
  },
  {
    id: "53",
    product_id: "food1",
    name: "Chocolate",
    description: "Dark chocolate",
    price: "4.99",
    rating: "4.2",
    type: "food",
  },
  {
    id: "54",
    product_id: "clothes2",
    name: "Jeans",
    description: "Slim-fit jeans",
    price: "39.99",
    rating: "4.6",
    type: "clothes",
  },
  {
    id: "55",
    product_id: "electronics2",
    name: "Laptop",
    description: "Gaming laptop",
    price: "1299.99",
    rating: "4.9",
    type: "electronics",
  },
  {
    id: "56",
    product_id: "food2",
    name: "Bread",
    description: "Whole wheat bread",
    price: "2.99",
    rating: "4.3",
    type: "food",
  },
  {
    id: "57",
    product_id: "clothes3",
    name: "Dress",
    description: "Floral print dress",
    price: "49.99",
    rating: "4.7",
    type: "clothes",
  },
  {
    id: "58",
    product_id: "electronics3",
    name: "Headphones",
    description: "Wireless headphones",
    price: "99.99",
    rating: "4.7",
    type: "electronics",
  },
  {
    id: "59",
    product_id: "food3",
    name: "Milk",
    description: "Organic cow milk",
    price: "3.99",
    rating: "4.1",
    type: "food",
  },
  {
    id: "60",
    product_id: "clothes4",
    name: "Sweater",
    description: "Knit sweater",
    price: "29.99",
    rating: "4.4",
    type: "clothes",
  },
  {
    id: "61",
    product_id: "electronics4",
    name: "Smart TV",
    description: "55-inch 4K TV",
    price: "899.99",
    rating: "4.8",
    type: "electronics",
  },
  {
    id: "62",
    product_id: "food4",
    name: "Bananas",
    description: "Fresh bananas",
    price: "1.99",
    rating: "4.6",
    type: "food",
  },
  {
    id: "63",
    product_id: "clothes5",
    name: "Jacket",
    description: "Leather jacket",
    price: "79.99",
    rating: "4.7",
    type: "clothes",
  },
  {
    id: "64",
    product_id: "electronics5",
    name: "Tablet",
    description: "10-inch tablet",
    price: "299.99",
    rating: "4.5",
    type: "electronics",
  },
  {
    id: "65",
    product_id: "food5",
    name: "Eggs",
    description: "Free-range eggs",
    price: "2.49",
    rating: "4.4",
    type: "food",
  },
  {
    id: "66",
    product_id: "clothes6",
    name: "Shirt",
    description: "Button-down shirt",
    price: "24.99",
    rating: "4.3",
    type: "clothes",
  },
  {
    id: "67",
    product_id: "electronics6",
    name: "Smartwatch",
    description: "Fitness smartwatch",
    price: "149.99",
    rating: "4.6",
    type: "electronics",
  },
  {
    id: "68",
    product_id: "food6",
    name: "Yogurt",
    description: "Greek yogurt",
    price: "1.49",
    rating: "4.2",
    type: "food",
  },
  {
    id: "69",
    product_id: "clothes7",
    name: "Skirt",
    description: "Pleated skirt",
    price: "34.99",
    rating: "4.5",
    type: "clothes",
  },
  {
    id: "70",
    product_id: "electronics7",
    name: "Camera",
    description: "Mirrorless camera",
    price: "799.99",
    rating: "4.7",
    type: "electronics",
  },
  {
    id: "71",
    product_id: "food7",
    name: "Cereal",
    description: "Whole grain cereal",
    price: "3.49",
    rating: "4.3",
    type: "food",
  },
  {
    id: "72",
    product_id: "clothes8",
    name: "Sweatshirt",
    description: "Hooded sweatshirt",
    price: "27.99",
    rating: "4.6",
    type: "clothes",
  },
  {
    id: "73",
    product_id: "electronics8",
    name: "Wireless Speaker",
    description: "Portable wireless speaker",
    price: "129.99",
    rating: "4.5",
    type: "electronics",
  },
  {
    id: "74",
    product_id: "food8",
    name: "Salmon",
    description: "Fresh salmon fillet",
    price: "9.99",
    rating: "4.8",
    type: "food",
  },
  {
    id: "75",
    product_id: "clothes9",
    name: "Pants",
    description: "Straight-leg pants",
    price: "34.99",
    rating: "4.4",
    type: "clothes",
  },
  {
    id: "76",
    product_id: "electronics9",
    name: "Gaming Console",
    description: "Next-gen gaming console",
    price: "499.99",
    rating: "4.9",
    type: "electronics",
  },
  {
    id: "77",
    product_id: "food9",
    name: "Cheese",
    description: "Aged cheddar cheese",
    price: "5.99",
    rating: "4.7",
    type: "food",
  },
  {
    id: "78",
    product_id: "clothes10",
    name: "Blouse",
    description: "Silk blouse",
    price: "44.99",
    rating: "4.7",
    type: "clothes",
  },
  {
    id: "79",
    product_id: "electronics10",
    name: "Wireless Earbuds",
    description: "Noise-cancelling wireless earbuds",
    price: "149.99",
    rating: "4.5",
    type: "electronics",
  },
  {
    id: "80",
    product_id: "food10",
    name: "Apples",
    description: "Organic red apples",
    price: "3.49",
    rating: "4.4",
    type: "food",
  },
  {
    id: "81",
    product_id: "clothes11",
    name: "Coat",
    description: "Wool coat",
    price: "99.99",
    rating: "4.6",
    type: "clothes",
  },
  {
    id: "82",
    product_id: "electronics11",
    name: "Monitor",
    description: "27-inch 4K monitor",
    price: "399.99",
    rating: "4.8",
    type: "electronics",
  },
  {
    id: "83",
    product_id: "food11",
    name: "Pasta",
    description: "Whole wheat pasta",
    price: "1.99",
    rating: "4.3",
    type: "food",
  },
  {
    id: "84",
    product_id: "clothes12",
    name: "Sweatpants",
    description: "Jogger sweatpants",
    price: "29.99",
    rating: "4.5",
    type: "clothes",
  },
  {
    id: "85",
    product_id: "electronics12",
    name: "Wireless Router",
    description: "High-speed wireless router",
    price: "79.99",
    rating: "4.7",
    type: "electronics",
  },
  {
    id: "86",
    product_id: "food12",
    name: "Oranges",
    description: "Juicy oranges",
    price: "2.99",
    rating: "4.2",
    type: "food",
  },
  {
    id: "87",
    product_id: "clothes13",
    name: "Tunic",
    description: "Flowy tunic",
    price: "39.99",
    rating: "4.7",
    type: "clothes",
  },
  {
    id: "88",
    product_id: "electronics13",
    name: "External Hard Drive",
    description: "1TB external hard drive",
    price: "89.99",
    rating: "4.6",
    type: "electronics",
  },
  {
    id: "89",
    product_id: "food13",
    name: "Avocado",
    description: "Ripe avocado",
    price: "1.99",
    rating: "4.4",
    type: "food",
  },
  {
    id: "90",
    product_id: "clothes14",
    name: "Sweatshirt",
    description: "Graphic sweatshirt",
    price: "24.99",
    rating: "4.3",
    type: "clothes",
  },
  {
    id: "91",
    product_id: "electronics14",
    name: "Wireless Mouse",
    description: "Bluetooth wireless mouse",
    price: "49.99",
    rating: "4.7",
    type: "electronics",
  },
  {
    id: "92",
    product_id: "food14",
    name: "Strawberries",
    description: "Fresh strawberries",
    price: "3.99",
    rating: "4.1",
    type: "food",
  },
  {
    id: "93",
    product_id: "clothes15",
    name: "Blazer",
    description: "Tailored blazer",
    price: "59.99",
    rating: "4.5",
    type: "clothes",
  },
  {
    id: "94",
    product_id: "electronics15",
    name: "Printer",
    description: "Wireless all-in-one printer",
    price: "149.99",
    rating: "4.8",
    type: "electronics",
  },
  {
    id: "95",
    product_id: "food15",
    name: "Tomatoes",
    description: "Vine-ripened tomatoes",
    price: "2.49",
    rating: "4.6",
    type: "food",
  },
  {
    id: "96",
    product_id: "clothes16",
    name: "Sweater",
    description: "Cable-knit sweater",
    price: "39.99",
    rating: "4.7",
    type: "clothes",
  },
  {
    id: "97",
    product_id: "electronics16",
    name: "Smart Speaker",
    description: "Voice-controlled smart speaker",
    price: "99.99",
    rating: "4.7",
    type: "electronics",
  },
  {
    id: "98",
    product_id: "food16",
    name: "Potatoes",
    description: "Organic potatoes",
    price: "1.99",
    rating: "4.3",
    type: "food",
  },
  {
    id: "99",
    product_id: "clothes17",
    name: "Dress",
    description: "Maxi dress",
    price: "49.99",
    rating: "4.6",
    type: "clothes",
  },
  {
    id: "100",
    product_id: "electronics17",
    name: "Gaming Headset",
    description: "Wired gaming headset",
    price: "79.99",
    rating: "4.5",
    type: "electronics",
  },
  {
    id: "101",
    product_id: "food17",
    name: "Carrots",
    description: "Fresh carrots",
    price: "1.49",
    rating: "4.2",
    type: "food",
  },
];
